import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import HeaderComp from "../Components/HeaderComp";
import Carousel from "../Components/Carousel";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faSearch,
  faAmbulance,
  faAnchor,
  faCalculator,
} from "@fortawesome/free-solid-svg-icons";
import Footer from "../Components/Footer";
// import styles from '../styles/Home.module.css'
// import styles from 'styles/index.scss'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main>
        <div className="caro1">
          <HeaderComp />
          <Carousel />
        </div>
        <div className="container-fuid bg-light py-4">
          <div className="container ">
            <div className="row">
              <div className="col-md-3">
                <div className="card card1-text bg-light pb-5 pt-5">
                  <div className="d-flex justify-content-center align-items-center">
                    <div className="align-self-center">
                      <FontAwesomeIcon
                        className="card1-icon"
                        icon={faCalculator}
                      />
                      WASTE AUDIT
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-md-3">
                <div className="card card1-text bg-light pb-5 pt-5">
                  <div className="d-flex justify-content-center align-items-center">
                    <div className="align-self-center">
                      <FontAwesomeIcon
                        className="card1-icon"
                        icon={faCalculator}
                      />
                      ZERO WASTE
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-3">
                <div className="card card1-text bg-light pb-5 pt-5">
                  <div className="d-flex justify-content-center align-items-center">
                    <div className="align-self-center">
                      <FontAwesomeIcon
                        className="card1-icon"
                        icon={faCalculator}
                      />
                      ANIMAL FEEDING
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-md-3">
                <div className="card card1-text bg-light pb-5 pt-5">
                  <div className="d-flex justify-content-center align-items-center">
                    <div className="align-self-center">
                      <FontAwesomeIcon
                        className="card1-icon"
                        icon={faCalculator}
                      />
                      COMPOSTING
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div>
            <div className="card"></div>
          </div>
        </div>
      </main>

      <section id="services">
        <div className="container mt-5">
          <div className="row">
            <div className="col-md-4 card2 mb-2">
              <div className="card ">
                <img
                  src="/Product quality-amico.png"
                  className="card-img-top"
                  alt="..."
                />
                <div className="card-body">
                  <h5 className="card-title req-text text-success">Products</h5>
                  <p className="card-text">
                    Discover eco-friendly products that help reduce waste and
                    support a sustainable lifestyle with ease of purchase.
                  </p>
                  <a href="#" className="btn btn-success">
                    Read More
                  </a>
                </div>
              </div>
            </div>

            <div className="col-md-4 mb-2">
              <div className="card">
                <img
                  src="/Manufacturing Process-cuate.png"
                  className="card-img-top"
                  alt="..."
                />
                <div className="card-body">
                  <h5 className="card-title req-text text-success">
                    Industries
                  </h5>
                  <p className="card-text ">
                    Explore how various industries are innovating waste
                    management practices to reduce their environmental impact.
                  </p>
                  <a href="#" className="btn btn-success">
                    Read More
                  </a>
                </div>
              </div>
            </div>

            <div className="col-md-4 mb-2">
              <div className="card">
                <img
                  src="/Service 24_7-pana.png"
                  className="card-img-top"
                  alt="..."
                />
                <div className="card-body">
                  <h5 className="card-title text-success req-text">Services</h5>
                  <p className="card-text">
                    Find out about our comprehensive waste management services,
                    designed to meet your unique needs and requirements
                  </p>
                  <a href="#" className="btn btn-success">
                    Read More
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="request">
        <div className="container mt-5 bg-light py-5 px-5">
          <div>
            <h3 className="text-dark req-text">Waste mangement at its peak</h3>
          </div>
          <div className="d-flex justify-content-between">
            <div>
              {" "}
              <h5 className="text-dark req-text  mt-3">
                Request a quote or if in need immediate help, contact us at
                <a href="tel:+2348068681342" className="phone req-text">
                  {" "}
                  +2348068681342
                </a>
              </h5>
            </div>
            {/* <button
              type="button"
              className="btn btn-success btn-outline-success  me-5 text-dark"
            >
              Request Quote
             
            </button> */}

            <a href="#" className="btn btn-success">
              Request Quote
            </a>
          </div>
        </div>
      </section>
      <section id="foot">
        <Footer />
      </section>
      {/* <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </>
  );
}
